version: '3'

services: 

  nginx:
      build:
        context: nginx
      container_name: nginx
      ports:
       - "8080:80"
      depends_on: 
       - app
      networks:
       - network-desafio

  app:
    build: 
      context: node
    container_name: app
    tty: true
    ports:
       - "3000:3000"
    depends_on: 
       db:
        condition: service_healthy
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - network-desafio

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            timeout: 30s
            retries: 5
    volumes: 
      - ./mysql:/var/lib/mysql_db
      - "./bd-scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks: 
      - network-desafio

networks: 
  network-desafio:
    driver: bridge    